In [20]:
import numpy as np

In [21]:
Array1= np.array([1,2,3,4,5,6,7,8,9,10])

print(Array1)

print(f"EL arreglo contiene {Array1.size} elementos")

print(f"EL arreglo contiene elementos {Array1.dtype}")



[ 1  2  3  4  5  6  7  8  9 10]
EL arreglo contiene 10 elementos
EL arreglo contiene elementos int64


In [31]:
A= np.zeros((3,3))

B= np.ones((3,3))

D= np.arange(1,10)

E= D.reshape(3,3)



C= A+B+E

print(E)
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [35]:
mm= np.arange(10,50,5)
print(mm)

[10 15 20 25 30 35 40 45]


In [ ]:
np.eye(4,4)



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
arr1= np.array([12, 45, 7, 23, 56, 89, 34])

print(f"max: {arr1.max()} min: {arr1.min()} promedio: {arr1.mean()}")

max: 89 min: 7 promedio: 38.0


In [44]:
arr1=np.array([[1,2,3],[3,3,3],[5,9,1]])

print(arr1)

arr1.sum(axis=1)


[[1 2 3]
 [3 3 3]
 [5 9 1]]


array([ 6,  9, 15])